# 1. Create a 3x3x3 array with random values 

In [1]:
import numpy as np
array = np.random.random((3,3,3))
print(array)

[[[0.29085919 0.80930863 0.5892337 ]
  [0.03748368 0.32430765 0.85944066]
  [0.53529597 0.89889559 0.50235821]]

 [[0.92980972 0.02966388 0.16093539]
  [0.1499899  0.10287734 0.16790524]
  [0.9597702  0.67526648 0.85466392]]

 [[0.98585799 0.62365582 0.89908711]
  [0.6142092  0.34017688 0.89203978]
  [0.78431694 0.05212526 0.89804427]]]


# 2.Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [5]:
matrix = np.diag(1+np.arange(4),k=-1)
print(matrix)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


# 3.Create a 8x8 matrix and fill it with a checkerboard pattern

In [18]:
import numpy as np
matrix = np.zeros((8,8),dtype=int)
matrix[1::2,::2] = 1
matrix[::2,1::2] = 1
print(matrix)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


# 4. Normalize a 5x5 random matrix

In [23]:
matrix = np.random.random((5,5))
print("Original Matrix: ")
print(matrix)
normalized = (matrix - np.min(matrix))/np.ptp(matrix)
print("Normalized Matrix: ")
print(normalized)

Original Matrix: 
[[0.94699797 0.07071522 0.74913188 0.8596346  0.69627523]
 [0.54798697 0.22467776 0.05295488 0.2263679  0.65795916]
 [0.62344044 0.28018229 0.99038871 0.56178109 0.82755939]
 [0.6187267  0.5199661  0.15499505 0.68630046 0.07973193]
 [0.85826306 0.1496014  0.82563273 0.95895743 0.67209856]]
Normalized Matrix: 
[[0.95371328 0.01894569 0.74264122 0.86051911 0.68625681]
 [0.5280715  0.183184   0.         0.18498694 0.64538345]
 [0.60856089 0.24239301 1.         0.54278627 0.82630314]
 [0.60353254 0.49818047 0.10885052 0.67561631 0.02856419]
 [0.85905603 0.10309689 0.82424789 0.96647094 0.66046654]]


# 5.  How to find common values between two arrays?

In [27]:
array1 = np.array([0,1,2,3,4,5])
print("Array1: ",array1)
array2 = np.array([0,2,4,6,8,10])
print("Array2: ",array2)
print("Common values between two arrays:")
print(np.intersect1d(array1, array2))

Array1:  [0 1 2 3 4 5]
Array2:  [ 0  2  4  6  8 10]
Common values between two arrays:
[0 2 4]


# 6.How to get the dates of yesterday, today and tomorrow?

In [29]:
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
print("Yestraday: ",yesterday)
today = np.datetime64('today', 'D')
print("Today: ",today)
tomorrow = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print("Tomorrow: ",tomorrow)

Yestraday:  2020-07-25
Today:  2020-07-26
Tomorrow:  2020-07-27


# 7. Consider two random array A and B, check if they are equal

In [39]:
array1 = np.random.randint(0,2,3)
print("Array1: ",array1)
array2 = np.random.randint(0,2,3)
print("Array2: ",array2)
array_equal = np.allclose(array1, array2)
if array_equal == True:
    print("The arrays are equal")
else:
    print("The arrays are not equal")

Array1:  [0 1 1]
Array2:  [0 1 1]
The arrays are equal


# 8.Create random vector of size 10 and replace the maximum value by 0 

In [44]:
array = np.random.randint(0,10,10)
print("Array:")
print(array)
array[array.argmax()] = 0
print("Replace the maximum value by 0:")
print(array)

Array:
[1 8 2 4 2 4 0 7 1 5]
Replace the maximum value by 0:
[1 0 2 4 2 4 0 7 1 5]


# 9. How to print all the values of an array?

In [54]:
np.set_printoptions()
x = np.ones((10, 10))
print(x)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


# 10.Subtract the mean of each row of a matrix

In [60]:
print("Matrix:")
matrix = np.random.rand(4, 4)
print(matrix)
print(" ")
print("Subtract the mean of each row of Matrix:")
new_matrix = matrix - matrix.mean(axis=1, keepdims=True)
print(new_matrix)

Matrix:
[[0.38193537 0.4736971  0.14357864 0.14361059]
 [0.72307413 0.39985482 0.51814846 0.76115899]
 [0.48430802 0.80434137 0.12870168 0.45714411]
 [0.86662319 0.92160768 0.59981891 0.87278766]]
 
Subtract the mean of each row of Matrix:
[[ 0.09622994  0.18799168 -0.14212679 -0.14209484]
 [ 0.12251503 -0.20070428 -0.08241064  0.16059989]
 [ 0.01568422  0.33571758 -0.33992211 -0.01147968]
 [ 0.05141383  0.10639832 -0.21539045  0.0575783 ]]


# 11.Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? 

# 12.How to get the diagonal of a dot product?

In [64]:
matrix1 = np.arange(9).reshape(3, 3)
print("Matrix1:")
print(matrix1)
matrix2 = np.arange(9).reshape(3, 3)
print("Matrix2:")
print(matrix2)
matrix_producto = np.dot(matrix1, matrix2)
print("Matrix Porducto:")
print(matrix_producto)
print("Diagonal of a dot product")
print(np.diag(matrix_producto))

Matrix1:
[[0 1 2]
 [3 4 5]
 [6 7 8]]
Matrix2:
[[0 1 2]
 [3 4 5]
 [6 7 8]]
Matrix Porducto:
[[ 15  18  21]
 [ 42  54  66]
 [ 69  90 111]]
Diagonal of a dot product
[ 15  54 111]


# 13.How to find the most frequent value in an array?

In [66]:
import numpy as np
array = np.random.randint(0, 5, 10)
print("Array:")
print(array)
print("Most frequent value in Array:")
print(np.bincount(array).argmax())

Array:
[0 2 2 0 1 1 3 3 2 1]
Most frequent value in Array:
1


# 14.How to get the n largest values of an array

In [74]:
import numpy as np
array = np.random.randint(0, 5, 10)
print("Array:")
print(array)
np.random.shuffle(array)
n = 1
print("The n largest values of Array:")
print(array[np.argsort(array)[-n:]])


Array:
[0 2 2 2 0 1 1 0 3 0]
The n largest values of Array:
[3]


# 15.How to create a record array from a regular array?

In [79]:
import numpy as np
array = np.array([(1,"Jhonatan Camasca Huamán", 15),
                 (2,"Virginia Monroy Malca", 20),
             (3,"Fernando Camasca Monroy", 19)])
print("Regular Array:")
print(array)
print("\nRecord Array:")
record_array = np.core.records.fromarrays(array.T,
                              names='col1, col2, col3')
print(record_array)

Regular Array:
[['1' 'Jhonatan Camasca Huamán' '15']
 ['2' 'Virginia Monroy Malca' '20']
 ['3' 'Fernando Camasca Monroy' '19']]

Record Array:
[('1', 'Jhonatan Camasca Huamán', '15')
 ('2', 'Virginia Monroy Malca', '20')
 ('3', 'Fernando Camasca Monroy', '19')]
